config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :therapists
  resources :users
  resources :top
  resources :explanation, only: [:index]
  resources :booking
  resources :how_to_use
  root 'top#index'

end

app/models/therapist.rb
class Therapist < ActiveRecord::Base
end

app/models/top.rb
class Top < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!, :only => [:show, :index]

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController

  before_action :authenticate_user!

  def index
  end

end

app/controllers/explanation_controller.rb
class ExplanationController < ApplicationController


  def index
    end

end

app/controllers/how_to_use_controller.rb
class HowToUseController < ApplicationController
  def index
    end
end

app/controllers/therapists_controller.rb
class TherapistsController < ApplicationController
  before_action :set_therapist, only: [:show, :edit, :update, :destroy]

  # GET /therapists
  # GET /therapists.json
  def index
    @therapists = Therapist.all
  end

  # GET /therapists/1
  # GET /therapists/1.json
  def show
  end

  # GET /therapists/new
  def new
    @therapist = Therapist.new
  end

  # GET /therapists/1/edit
  def edit
  end

  # POST /therapists
  # POST /therapists.json
  def create
    @therapist = Therapist.new(therapist_params)

    respond_to do |format|
      if @therapist.save
        format.html { redirect_to @therapist, notice: 'Therapist was successfully created.' }
        format.json { render :show, status: :created, location: @therapist }
      else
        format.html { render :new }
        format.json { render json: @therapist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /therapists/1
  # PATCH/PUT /therapists/1.json
  def update
    respond_to do |format|
      if @therapist.update(therapist_params)
        format.html { redirect_to @therapist, notice: 'Therapist was successfully updated.' }
        format.json { render :show, status: :ok, location: @therapist }
      else
        format.html { render :edit }
        format.json { render json: @therapist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /therapists/1
  # DELETE /therapists/1.json
  def destroy
    @therapist.destroy
    respond_to do |format|
      format.html { redirect_to therapists_url, notice: 'Therapist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_therapist
      @therapist = Therapist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def therapist_params
      params[:therapist]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/explanation_helper.rb
module ExplanationHelper
end

app/helpers/how_to_use_helper.rb
module HowToUseHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/explanation/index.html.erb
<div class="main_contents">
  心ワークスとは
</div>

app/views/how_to_use/index.html.erb
<div class="main_contents">
  心ワークスの使い方
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
<meta charset="UTF-8" />

<title>心ワークス</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

</head>
<body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/top">心ワークス</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="/explanation">心ワークスの特徴</a></li>
                <li><%= link_to'心理士一覧', therapists_path %></li>
                <li><%= link_to'ご利用方法', how_to_use_index_path %></li>
                <li><a href="/booking">ご予約</a></li>
                <li><%= link_to'会員登録', new_user_registration_path %></li>
                <li><%= link_to'ログイン', new_user_session_path %></li>
                <li class="column">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">コラム <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>

  <%= bootstrap_flash %>
  <%= yield %>

</body>
 <!-- FOOTER -->
<div class = "footer">
        <p class="pull-right"><a href="#">トップに戻る</a></p>
        <p>&copy; HIKARI Lab, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</div>

app/views/therapists/_form.html.erb
<%= form_for(@therapist) do |f| %>
  <% if @therapist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@therapist.errors.count, "error") %> prohibited this therapist from being saved:</h2>

      <ul>
      <% @therapist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/therapists/edit.html.erb
<h1>Editing Therapist</h1>

<%= render 'form' %>

<%= link_to 'Show', @therapist %> |
<%= link_to 'Back', therapists_path %>

app/views/therapists/index.html.erb
<div class = "main_contents therapists">
<p id="notice"><%= notice %></p>

<h1>Listing Therapists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @therapists.each do |therapist| %>
      <tr>
        <td><%= link_to 'Show', therapist %></td>
        <td><%= link_to 'Edit', edit_therapist_path(therapist) %></td>
        <td><%= link_to 'Destroy', therapist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Therapist', new_therapist_path %>
</div>

app/views/therapists/new.html.erb
<div class ="main_contents">
<h1>New Therapist</h1>

<%= render 'form' %>

<%= link_to 'Back', therapists_path %>
</div>

app/views/therapists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_therapist_path(@therapist) %> |
<%= link_to 'Back', therapists_path %>

app/views/top/index.html.erb
<!--     <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">心ワークス</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="/explanation">心ワークスの特徴</a></li>
                <li><a href="#therapists">心理士一覧</a></li>
                <li><a href="#how_to_use">ご利用方法</a></li>
                <li><a href="#booking">ご予約</a></li>
                <li><a href="#sign_up">会員登録</a></li>
                <li><a href="#log_in">ログイン</a></li>
                <li class="column">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">コラム <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div> -->


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src = "/top/4790f3b24d5e82d5285c4797f125bee2_s.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h3>心理ケアは受けてみたいものの、会社のケアは使いたくない方</h3>
              <h3>今まで元気だったのに、最近調子が優れない方</h3>
              <h3>これまでなんとなく心理ケアを避けていた方</h3>
              <p>そんな方々のために、心ワークスには、一流の臨床心理士・効果が実証された心理療法・安心できるコミュニケーションツールが揃っています。</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="https://www.pakutaso.com/assets_c/2015/06/AXIS93_gardens-thumb-1000xauto-17034.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="https://www.pakutaso.com/assets_c/2015/06/PAK85_notepc20150319202127-thumb-1000xauto-18289.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <!-- <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="85" height="85"> -->
          <span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>
          <h2>セキュリティの高いビデオ通信</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="/explanation" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <!-- <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="85" height="85"> -->
          <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
          <h2>臨床心理士によるカウンセリング</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-default" href="/explanation" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->



        <div class="col-lg-4">
         <!--  <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="85" height="85"> -->
<!--           <span class="glyphicons-hospital" aria-hidden="true"></span> -->
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <h2>厚生労働省のマニュアルに基づく心理療法</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="/explanation" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->


        <div class="col-lg-4">
<!--           <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
 -->

          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>

          <h2>セラピスト1</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="/therapists" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">どんな人がカウンセリングをうけるの？ <span class="text-muted">
          これまでずっと元気だった、そんなあなたもご利用いただけます。</span></h2>
          <p class="lead">日本では、あまり馴染みのないカウンセリングですが、
          実は海外では、自分の専属のカウンセラーを持っていることは珍しくはありません。</p>
          <p class="lead">日常生活をメインテナンスし、充実した日々を過ごすためには、なんでも話すことのできる場があることはとても重要と考えられているためです。</p> 
          <p class="lead">というのも、自分の悩み・不安・憂うつな気持ち・ドキドキやそわそわする感じ・発達障害の疑いは、</p>
          <p class="lead">利害関係のある、家族・恋人・友人・上司・同僚には、正直に話すことが難しいことがほとんどだからです。</p>

          <p class="lead">しかし、誰にも言うことができず心に溜めてしまうと、身体症状があらわれ、社会生活に支障をきたしてしまうこともあります。</p>

          <p class="lead">心ワークスでは、そのような悪化を回避・改善するために、最新の研究に基づいた、効果のある心理療法を用いて、一流の心理士が社会生活を円滑に過ごすサポートをいたします。</p>

          <p class="lead">例えば、下記のようなことを最近感じている場合、私たちがサポートできるかもしれません。</p>

          <p class="lead">・あれ？ちょっといつもと違うな</p>
          <p class="lead">・ずっとあのことで頭が一杯になっているな</p>
          <p class="lead">・しばらく気持ちが塞ぎ込んでいるな</p>
          <p class="lead">・仕事に集中するのが難しい
            </p>
            <p class="lead">・自分は発達障害なのか？どうやったらもっとうまく人と関わることができるのか？</p>
          </p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="https://www.pakutaso.com/assets_c/2015/09/150724261193-thumb-815xauto-19179.jpg" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">他のカウンセリングとどう違うの？ <span class="text-muted">心ワークスは、専門性・効果・安全性を重視しています。</span></h2>
          <p class="lead">
          1. 専門性
          心ワークスでは、厳選されたセラピストのみを採用しています。

          心理ケアを行うには、しっかりとしたトレーニングを受けることがとても大切です。
          しかし日本では、きちんとしたトレーニングを受けていないカウンセラーやセラピストがとても多く、残念ながら、ただ話を聞くだけだったり、求めていないアドバイスをしてきたり、場合によってはお説教をしたり、全然話を聞いてくれない、といったこともあります。

          そのような事態を避けるために、心ワークスでは、セラピストの質を大変重視しています。心ワークスのセラピストは全員、厳選した採用過程を通過し、きちんとした資格を持ち（資格取得見込み者も含む）、大学院で最低２年間のトレーニングを終了しています。また、その質を維持・向上できるよう、心ワークスでは、カウンセリングの状況を把握し、定期的にセラピストのトレーニングを行っています。

          2. 効果
          心ワークスでは、研究によって効果が実証されている心理療法を積極的に用います。
          心理療法は様々ありますが、その中でも認知行動療法は特に抑うつや不安に効果が認められています。ただ、日本では認知行動療法をお客様ごとの特徴を考慮しながら使いこなすことができる心理士は多くありません。心ワークスでは、トレーニングをしっかりと積んだ心理士による、厚生労働省が出したマニュアルに沿った認知行動療法を行うことが可能です。（お客様ごとに問題の内容は異なるので、まずはお話を聞いてから方針を決定します。）
          また、発達障害に対しても、最新の知見を活かしながら、お客様一人一人の状況を把握し、人と関わるコツや仕事を円滑に行うコツなどについて話し合うことができます。

          3. 安全性
          心ワークスでは、安全性の高いコミュニケーションツール を使用し、セラピストはモニタリングされた状態でカウンセリングを行っています。

          まず、心ワークスでは国内で最も安全性が高く、会話の内容がしっかりと守られるコミュニケーションツールのを使用しています。こちらは、無料コミュニケーションツールとは異なり、バグやシステムトラブルも少ないため、安定してお客様が安心できるサービスをお届けできます。

          また、オンラインカウンセリングは、セラピストの自宅で行うものが多いのですが、それではきちんとしたサービスが提供されない可能性もあります。心ワークスでは、セラピストは心ワークスの専用カウンセリングルームで、監視された状態でカウンセリングを行っているので、常に緊張感をもちながらプロとしてお客様と向き合います。</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" src="https://www.pakutaso.com/assets_c/2015/05/PAK58_kiokuyorikiroku-thumb-815xauto-15605.jpg">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">カウンセリングを受けるとどうなるの？ <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="https://www.pakutaso.com/assets_c/2015/05/PAK86_komorebitohizashi-thumb-815xauto-15943.jpg" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <!-- <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer> -->

    </div><!-- /.container -->

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if user_signed_in? %>

<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

  </ul>
</div>
<h1>マイページです！</h1>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>